/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Uttam Kirana - Grocery Shop Management API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Send OTP to mobile number
 */
export const SendOtpBody = zod.object({
  mobile: zod.string(),
});

export const SendOtpResponse = zod.object({
  message: zod.string(),
  otp: zod.string().optional().describe("Simulated OTP (returned in dev mode)"),
});

/**
 * @summary Verify OTP and login/register
 */
export const VerifyOtpBody = zod.object({
  mobile: zod.string(),
  otp: zod.string(),
  name: zod.string().optional(),
});

export const VerifyOtpResponse = zod.object({
  token: zod.string(),
  user: zod.object({
    id: zod.number(),
    mobile: zod.string(),
    name: zod.string().optional(),
    role: zod.enum(["customer", "admin", "delivery"]),
    address: zod.string().nullish(),
    city: zod.string().nullish(),
    pincode: zod.string().nullish(),
    walletBalance: zod.number(),
    rewardPoints: zod.number(),
    createdAt: zod.coerce.date(),
  }),
});

/**
 * @summary Get current user profile
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  mobile: zod.string(),
  name: zod.string().optional(),
  role: zod.enum(["customer", "admin", "delivery"]),
  address: zod.string().nullish(),
  city: zod.string().nullish(),
  pincode: zod.string().nullish(),
  walletBalance: zod.number(),
  rewardPoints: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update delivery address
 */
export const UpdateAddressBody = zod.object({
  address: zod.string(),
  city: zod.string().optional(),
  pincode: zod.string().optional(),
});

export const UpdateAddressResponse = zod.object({
  id: zod.number(),
  mobile: zod.string(),
  name: zod.string().optional(),
  role: zod.enum(["customer", "admin", "delivery"]),
  address: zod.string().nullish(),
  city: zod.string().nullish(),
  pincode: zod.string().nullish(),
  walletBalance: zod.number(),
  rewardPoints: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Get all product categories
 */
export const GetCategoriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  icon: zod.string().nullish(),
  color: zod.string().nullish(),
});
export const GetCategoriesResponse = zod.array(GetCategoriesResponseItem);

/**
 * @summary Create a new category (admin)
 */
export const CreateCategoryBody = zod.object({
  name: zod.string(),
  slug: zod.string(),
  icon: zod.string().optional(),
  color: zod.string().optional(),
});

/**
 * @summary Delete a category (admin)
 */
export const DeleteCategoryParams = zod.object({
  categoryId: zod.coerce.number(),
});

export const DeleteCategoryResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Update a category (admin)
 */
export const UpdateCategoryParams = zod.object({
  categoryId: zod.coerce.number(),
});

export const UpdateCategoryBody = zod.object({
  name: zod.string(),
  slug: zod.string(),
  icon: zod.string().optional(),
  color: zod.string().optional(),
});

export const UpdateCategoryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  icon: zod.string().nullish(),
  color: zod.string().nullish(),
});

/**
 * @summary List products with search/filter
 */
export const getProductsQueryLimitDefault = 50;
export const getProductsQueryOffsetDefault = 0;

export const GetProductsQueryParams = zod.object({
  search: zod.coerce.string().optional(),
  category: zod.coerce.string().optional(),
  inStock: zod.coerce.boolean().optional(),
  minPrice: zod.coerce.number().optional(),
  maxPrice: zod.coerce.number().optional(),
  limit: zod.coerce.number().default(getProductsQueryLimitDefault),
  offset: zod.coerce.number().default(getProductsQueryOffsetDefault),
});

export const GetProductsResponse = zod.object({
  products: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      description: zod.string().nullish(),
      price: zod.number(),
      mrp: zod.number().nullish(),
      unit: zod.string(),
      stock: zod.number(),
      categoryId: zod.number(),
      categoryName: zod.string().nullish(),
      imageUrl: zod.string().nullish(),
      isActive: zod.boolean(),
      isFeatured: zod.boolean(),
      discount: zod.number().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create a new product (admin)
 */
export const CreateProductBody = zod.object({
  name: zod.string(),
  description: zod.string().optional(),
  price: zod.number(),
  mrp: zod.number().optional(),
  unit: zod.string(),
  stock: zod.number(),
  categoryId: zod.number(),
  imageUrl: zod.string().optional(),
  isFeatured: zod.boolean().optional(),
  discount: zod.number().optional(),
});

/**
 * @summary Get featured/offer products for home banner
 */
export const GetFeaturedProductsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  mrp: zod.number().nullish(),
  unit: zod.string(),
  stock: zod.number(),
  categoryId: zod.number(),
  categoryName: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  isActive: zod.boolean(),
  isFeatured: zod.boolean(),
  discount: zod.number().nullish(),
  createdAt: zod.coerce.date(),
});
export const GetFeaturedProductsResponse = zod.array(
  GetFeaturedProductsResponseItem,
);

/**
 * @summary Get single product detail
 */
export const GetProductParams = zod.object({
  productId: zod.coerce.number(),
});

export const GetProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  mrp: zod.number().nullish(),
  unit: zod.string(),
  stock: zod.number(),
  categoryId: zod.number(),
  categoryName: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  isActive: zod.boolean(),
  isFeatured: zod.boolean(),
  discount: zod.number().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update product (admin)
 */
export const UpdateProductParams = zod.object({
  productId: zod.coerce.number(),
});

export const UpdateProductBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().optional(),
  price: zod.number().optional(),
  mrp: zod.number().optional(),
  unit: zod.string().optional(),
  stock: zod.number().optional(),
  categoryId: zod.number().optional(),
  imageUrl: zod.string().optional(),
  isActive: zod.boolean().optional(),
  isFeatured: zod.boolean().optional(),
  discount: zod.number().optional(),
});

export const UpdateProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  mrp: zod.number().nullish(),
  unit: zod.string(),
  stock: zod.number(),
  categoryId: zod.number(),
  categoryName: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  isActive: zod.boolean(),
  isFeatured: zod.boolean(),
  discount: zod.number().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete product (admin)
 */
export const DeleteProductParams = zod.object({
  productId: zod.coerce.number(),
});

export const DeleteProductResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Update product stock (admin)
 */
export const UpdateStockParams = zod.object({
  productId: zod.coerce.number(),
});

export const UpdateStockBody = zod.object({
  stock: zod.number(),
});

export const UpdateStockResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  mrp: zod.number().nullish(),
  unit: zod.string(),
  stock: zod.number(),
  categoryId: zod.number(),
  categoryName: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  isActive: zod.boolean(),
  isFeatured: zod.boolean(),
  discount: zod.number().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Get current user cart
 */
export const GetCartResponse = zod.object({
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      imageUrl: zod.string().nullish(),
      unit: zod.string(),
      quantity: zod.number(),
      subtotal: zod.number(),
    }),
  ),
  itemCount: zod.number(),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
});

/**
 * @summary Clear the cart
 */
export const ClearCartResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Add item to cart
 */
export const AddToCartBody = zod.object({
  productId: zod.number(),
  quantity: zod.number(),
});

export const AddToCartResponse = zod.object({
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      imageUrl: zod.string().nullish(),
      unit: zod.string(),
      quantity: zod.number(),
      subtotal: zod.number(),
    }),
  ),
  itemCount: zod.number(),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
});

/**
 * @summary Update cart item quantity
 */
export const UpdateCartItemParams = zod.object({
  productId: zod.coerce.number(),
});

export const UpdateCartItemBody = zod.object({
  productId: zod.number(),
  quantity: zod.number(),
});

export const UpdateCartItemResponse = zod.object({
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      imageUrl: zod.string().nullish(),
      unit: zod.string(),
      quantity: zod.number(),
      subtotal: zod.number(),
    }),
  ),
  itemCount: zod.number(),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
});

/**
 * @summary Remove item from cart
 */
export const RemoveCartItemParams = zod.object({
  productId: zod.coerce.number(),
});

export const RemoveCartItemResponse = zod.object({
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      imageUrl: zod.string().nullish(),
      unit: zod.string(),
      quantity: zod.number(),
      subtotal: zod.number(),
    }),
  ),
  itemCount: zod.number(),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
});

/**
 * @summary Get user orders (or all orders for admin)
 */
export const getOrdersQueryLimitDefault = 20;
export const getOrdersQueryOffsetDefault = 0;

export const GetOrdersQueryParams = zod.object({
  status: zod.coerce.string().optional(),
  limit: zod.coerce.number().default(getOrdersQueryLimitDefault),
  offset: zod.coerce.number().default(getOrdersQueryOffsetDefault),
});

export const GetOrdersResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userName: zod.string().nullish(),
  userMobile: zod.string().nullish(),
  deliveryBoyId: zod.number().nullish(),
  deliveryBoyName: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      subtotal: zod.number(),
      unit: zod.string(),
    }),
  ),
  status: zod.enum([
    "placed",
    "confirmed",
    "packed",
    "out_for_delivery",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  paymentStatus: zod.enum(["pending", "paid", "failed"]),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
  deliveryAddress: zod.string(),
  notes: zod.string().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const GetOrdersResponse = zod.array(GetOrdersResponseItem);

/**
 * @summary Place an order
 */
export const CreateOrderBody = zod.object({
  paymentMethod: zod.enum(["cod", "online"]),
  deliveryAddress: zod.string(),
  notes: zod.string().optional(),
});

/**
 * @summary Get order details
 */
export const GetOrderParams = zod.object({
  orderId: zod.coerce.number(),
});

export const GetOrderResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userName: zod.string().nullish(),
  userMobile: zod.string().nullish(),
  deliveryBoyId: zod.number().nullish(),
  deliveryBoyName: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      subtotal: zod.number(),
      unit: zod.string(),
    }),
  ),
  status: zod.enum([
    "placed",
    "confirmed",
    "packed",
    "out_for_delivery",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  paymentStatus: zod.enum(["pending", "paid", "failed"]),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
  deliveryAddress: zod.string(),
  notes: zod.string().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Update order status (admin/delivery)
 */
export const UpdateOrderStatusParams = zod.object({
  orderId: zod.coerce.number(),
});

export const UpdateOrderStatusBody = zod.object({
  status: zod.enum([
    "placed",
    "confirmed",
    "packed",
    "out_for_delivery",
    "delivered",
    "cancelled",
  ]),
});

export const UpdateOrderStatusResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userName: zod.string().nullish(),
  userMobile: zod.string().nullish(),
  deliveryBoyId: zod.number().nullish(),
  deliveryBoyName: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      subtotal: zod.number(),
      unit: zod.string(),
    }),
  ),
  status: zod.enum([
    "placed",
    "confirmed",
    "packed",
    "out_for_delivery",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  paymentStatus: zod.enum(["pending", "paid", "failed"]),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
  deliveryAddress: zod.string(),
  notes: zod.string().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Assign delivery boy to order (admin)
 */
export const AssignDeliveryParams = zod.object({
  orderId: zod.coerce.number(),
});

export const AssignDeliveryBody = zod.object({
  deliveryBoyId: zod.number(),
});

export const AssignDeliveryResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userName: zod.string().nullish(),
  userMobile: zod.string().nullish(),
  deliveryBoyId: zod.number().nullish(),
  deliveryBoyName: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      subtotal: zod.number(),
      unit: zod.string(),
    }),
  ),
  status: zod.enum([
    "placed",
    "confirmed",
    "packed",
    "out_for_delivery",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  paymentStatus: zod.enum(["pending", "paid", "failed"]),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
  deliveryAddress: zod.string(),
  notes: zod.string().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Get orders assigned to delivery boy
 */
export const GetDeliveryOrdersResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userName: zod.string().nullish(),
  userMobile: zod.string().nullish(),
  deliveryBoyId: zod.number().nullish(),
  deliveryBoyName: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      subtotal: zod.number(),
      unit: zod.string(),
    }),
  ),
  status: zod.enum([
    "placed",
    "confirmed",
    "packed",
    "out_for_delivery",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  paymentStatus: zod.enum(["pending", "paid", "failed"]),
  subtotal: zod.number(),
  deliveryCharge: zod.number(),
  total: zod.number(),
  deliveryAddress: zod.string(),
  notes: zod.string().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const GetDeliveryOrdersResponse = zod.array(
  GetDeliveryOrdersResponseItem,
);

/**
 * @summary Get all users (admin)
 */
export const GetAdminUsersResponseItem = zod.object({
  id: zod.number(),
  mobile: zod.string(),
  name: zod.string().optional(),
  role: zod.enum(["customer", "admin", "delivery"]),
  address: zod.string().nullish(),
  city: zod.string().nullish(),
  pincode: zod.string().nullish(),
  walletBalance: zod.number(),
  rewardPoints: zod.number(),
  createdAt: zod.coerce.date(),
});
export const GetAdminUsersResponse = zod.array(GetAdminUsersResponseItem);

/**
 * @summary Get all delivery boys
 */
export const GetDeliveryBoysResponseItem = zod.object({
  id: zod.number(),
  mobile: zod.string(),
  name: zod.string().optional(),
  role: zod.enum(["customer", "admin", "delivery"]),
  address: zod.string().nullish(),
  city: zod.string().nullish(),
  pincode: zod.string().nullish(),
  walletBalance: zod.number(),
  rewardPoints: zod.number(),
  createdAt: zod.coerce.date(),
});
export const GetDeliveryBoysResponse = zod.array(GetDeliveryBoysResponseItem);

/**
 * @summary Get sales summary stats (admin)
 */
export const GetAnalyticsSummaryResponse = zod.object({
  totalOrders: zod.number(),
  totalRevenue: zod.number(),
  todayOrders: zod.number(),
  todayRevenue: zod.number(),
  totalCustomers: zod.number(),
  pendingOrders: zod.number(),
  outForDeliveryOrders: zod.number(),
  averageOrderValue: zod.number(),
});

/**
 * @summary Get top selling products
 */
export const getTopProductsQueryLimitDefault = 10;

export const GetTopProductsQueryParams = zod.object({
  limit: zod.coerce.number().default(getTopProductsQueryLimitDefault),
});

export const GetTopProductsResponseItem = zod.object({
  productId: zod.number(),
  productName: zod.string(),
  totalSold: zod.number(),
  revenue: zod.number(),
  imageUrl: zod.string().nullish(),
});
export const GetTopProductsResponse = zod.array(GetTopProductsResponseItem);

/**
 * @summary Get order counts grouped by status
 */
export const GetOrdersByStatusResponseItem = zod.object({
  status: zod.string(),
  count: zod.number(),
});
export const GetOrdersByStatusResponse = zod.array(
  GetOrdersByStatusResponseItem,
);
