kind = "web"
previewPath = "/"
title = "Uttam Kirana"
version = "1.0.0"
id = "artifacts/uttam-kirana"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20231

[services.development]
run = "pnpm --filter @workspace/uttam-kirana run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/uttam-kirana", "run", "build" ]
publicDir = "artifacts/uttam-kirana/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20231"
BASE_PATH = "/"
